- pages/index.tsx
> FILMDOMS feat: 테스트 텍스트 추가

- components/views/Layout/Header/Header.tsx
- components/views/Layout/SideNav/SideNav.tsx
- package.json
- yarn.lock
<작업 내용>
- sharp 패키지 추가
- header, sidenav 리팩토링
<첨부>
- #31
> FILMDOMS #31 production에서의 이미지 최적화를 위한 sharp 패키지 추가 및 VoidFuncion 리팩토링

- components/views/Home/Banner/BannerContainer.stories.tsx
- components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.stories.tsx
제목 : FILMDOMS #56 스토리북 디자인 불일치 수정
<작업 내용>
- Banner 스토리 픽셀값 설정 및 Wrapper 추가
- Slider 스토리 픽셀값 설정 및 Wrapper 추가
<첨부>
- ISSUE #56
> FILMDOMS #56 스토리북 디자인 불일치 수정

- components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.tsx
제목 : FILMDOMS #59 Largest Contentful Paint element에 대한 우선 로딩 적용
<작업 내용>
- priority props 추가
<첨부>
- ISSUE #59
> FILMDOMS #59 Largest Contentful Paint element에 대한 우선 로딩 적용

- components/views/Home/Notice/Notice.tsx
- mocks/handlers/notice/index.ts
제목 : FILMDOMS #63 날짜 형식 변경
<작업 내용>
- 날짜 출력 변경 그리드 조정
- 글자 수 제한
<첨부>
- ISSUE #63
> FILMDOMS #63 날짜 형식 변경

- components/views/Article/Main/ArticlePage.stories.tsx
- components/views/Article/Popular/ArticlePopular.tsx
- components/views/Article/Popular/ArticlePopularContainer.stories.tsx
- components/views/Article/Popular/ArticlePopularContainer.tsx
- mocks/handlers/index.ts
- mocks/handlers/popular/data/index.ts
- mocks/handlers/popular/index.ts
- pages/article/[category]/[id]/index.tsx
- pages/article/[category]/index.tsx
- services/popular/apis.ts
- services/popular/index.ts
- services/popular/queries.ts
- services/queryKeys.ts
제목 : FILMDOMS #69  [인기 게시글 구현]
- 인기 게시글 퍼블리싱
<첨부>
- ISSUE #69
> FILMDOMS #69  [인기 게시글 구현] coded by 시형

- components/views/Home/Critic/CriticContainer.tsx
제목 : FILMDOMS #77 critic 섹션 상단 여백 추가
critic 섹션 상단 여백 부분 디자인과 맞지 않아 수정
<첨부>
- 디자인 
- 기존 
- 현재 
- ISSUE #77
> style: critic 섹션 상단 여백 추가

- components/views/Article/Detail/Comment/CommentItem.stories.tsx
- components/views/Article/Detail/Comment/CommentItem.tsx
- services/article/apis.ts
- types/pages/article.d.ts
<작업 내용>
- 기존 likes가 빠진 댓글 DTO를 변경된 서버 api 명세에 맞춥니다.
<첨부>
- ISSUE close #92
> FILMDOMS #92 댓글 DTO를 변경된 서버 api 명세에 맞춥니다

- components/views/MyPage/InterestMovieSection/InterestMovieSection.tsx
- components/views/MyPage/UserInfoSection/UserInfoSection.tsx
- components/views/MyPage/constants.ts
<작업 내용>
<첨부>
- 작업 결과
- ISSUE #99 
- ISSUE #100
> FILMDOMS #100 마이페이지 디자인 변경사항을 수정합니다

- pages/_app.tsx
제목 : FILMDOMS #105 FIX build error resolve
<작업 내용>
- _app.tsx 수정
<첨부>
[관련된 이슈나 PR, 커밋을 언급하세요, 아래는 예시입니다]
> FILMDOMS #105 FIX build error resolve

- pages/_app.tsx
제목 : FILMDOMS #105 FIX page props 구조 분해 할당 부분 수정
<작업 내용>
- pageProps 할당 부분 수정
<첨부>
> FILMDOMS #105 FIX page props 구조 분해 할당 부분 수정

- components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
- components/views/Auth/SignUp/SignUpForm/style.ts
<작업 내용>
- 인증번호 확인 배치를 수정합니다.
<첨부>
- before
- after
- ISSUE #102
> FILMDOMS #102 회원가입 페이지 디자인 변경에 따른 수정입니다

- components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
- components/views/Auth/SignUp/SignUpForm/constants.ts
- components/views/Auth/SignUp/SignUpForm/utils.ts
- constants/auth/regex.ts
- services/api/index.ts
- services/auth/apis.ts
- services/auth/mutations.ts
- types/auth.d.ts
<작업 내용>
-  ISSUE #112
참고
- `Set-Cookie` 저장 테스트를 위해 임시 머지하겠습니다.(main)
<첨부>
- ISSUE #112
> FILMDOMS #112 SignUp 기능을 구현합니다

- components/common/Editor/Editor.tsx
- components/common/Editor/index.ts
- components/views/Article/Main/SearchForm/constants.ts
- components/views/Article/Write/Check/LabeledCheckbox.tsx
- components/views/Article/Write/Check/index.ts
- components/views/Article/Write/EditorContainer.tsx
- components/views/Article/Write/File/File.tsx
- components/views/Article/Write/File/index.ts
- components/views/Article/Write/index.ts
- components/views/Auth/Help/Email/Email.tsx
- components/views/Auth/Help/Email/index.ts
- components/views/Auth/Help/Header/Header.tsx
- components/views/Auth/Help/Header/index.ts
- components/views/Auth/Help/Help.tsx
- components/views/Auth/Help/Password/Password.tsx
- components/views/Auth/Help/Password/index.ts
- components/views/Auth/Help/index.ts
- components/views/Auth/SignIn/SignIn.tsx
- components/views/Auth/index.ts
- package.json
- pages/auth/help.tsx
- pages/write/article/[category]/index.tsx
- services/article/apis.ts
- services/article/index.ts
- services/article/mutations.ts
- services/auth/apis.ts
- services/auth/mutations.ts
- types/auth.d.ts
- types/pages/article.d.ts
- yarn.lock
제목 : FILMDOMS #90 비밀번호 변경, 게시물 작성, 로그인 로직 구현
<작업 내용>
- 로그인 기능 구현
- 비밀번호 변경 폼 생성
- 게시물 작성
<첨부>
- ISSUE #90
> FILMDOMS #90 비밀번호 변경, 게시물 작성(60%), 로그인 기능 구현

- components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
- services/api/index.ts
- services/api/utils.ts
- services/auth/apis.ts
- services/auth/mutations.ts
- services/myPage/apis.ts
<작업 내용>
- 회원가입 기능을 구현합니다.
- - 작성된 이메일로 인증번호 발송
- - 인증번호 확인
- - 닉네임 중복확인
- - 모든 조건 확인 후, 회원가입 API 호출
- 자동 로그인을 구현합니다.
- - `Refresh Token`을 사용하여 유효하다면 `Access Token`을 발급 받고 실패한 요청을 재요청합니다.
<첨부>
- ISSUE #112
> FILMDOMS #112 회원가입 페이지의 기능을 구현합니다

- components/views/About/Section/TopSection/TopSection.tsx
<작업 내용>
- 디자인과 동일하게 title을 작성합니다.
- `영화인을 위한, 영화인의공간` -> `영화인을 위한, 영화인의 공간`
<첨부>
- 수정 결과
- ISSUE #129
> FILMDOMS #129 About Title을 수정합니다

- components/views/Auth/SignIn/SignIn.tsx
- components/views/Auth/SignUp/SignUpContainer.tsx
- components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
- next.config.js
- pages/auth/google.tsx
- services/auth/apis.ts
- services/auth/mutations.ts
- services/auth/queries.ts
- types/auth.d.ts
제목 : FILMDOMS #125 Google OAUTH Login
<작업 내용>
- google oauth login 기능 구현
<첨부>
- ISSUE #125
> FILMDOMS #125 Google OAUTH Login

- components/views/Article/Main/TagList/TagList.tsx
<작업 내용>
- Tag `전체`를 `ALL`로 변경하여 통일합니다.
<첨부>
- 작업 결과
- ISSUE #132
> FILMDOMS #132 Tag를 영어로 변경합니다

- components/views/Article/Main/BoardContainer/ArticleBoard/CriticBoard.tsx
<작업 내용>
- Critic 하단 UI 속성을 변경합니다.
<첨부>
- 작업 결과
- ISSUE #134
> FILMDOMS #134 Critic 상세 게시글 하단 UI 이슈를 해결합니다

- components/views/Home/Community/Recent/Recent.tsx
- components/views/Home/Critic/CriticContainer.tsx
- components/views/Home/FilmUniverse/FilmUniverseContainer.tsx
<작업 내용>
- Recent 각 게시글 클릭 시, 각 상세 게시글로 이동합니다.
- FilmUniverse More 클릭 시, FilmUniverse 전체 게시글로 이동합니다.
- Critic More 클릭 시, Critic 전체 게시글로 이동합니다.
<첨부>
- ISSUE #135
> FILMDOMS #135 메인페이지 연결 링크를 최신화합니다

- components/views/Article/Main/Slide/Slider/data.ts
- components/views/Layout/Header/Header.tsx
- components/views/Search/SearchContainer.tsx
- components/views/Search/index.ts
- pages/search/index.tsx
<작업 내용>
- 검색 폼
- 기타 수정 사항
<첨부>
- ISSUE #142
> FILMDOMS #142 Search Form, 기타 수정 사항

- components/common/Editor/Editor.tsx
- components/views/Article/Detail/ArticleDetail.tsx
- components/views/Article/Detail/Comment/CommentItem.tsx
- services/article/apis.ts
- services/article/mutations.ts
- types/pages/article.d.ts
<작업 내용>
- 댓글 좋아요
- 아티클 좋아요
- 에디터 이미지 삽입
- 클립 보드 복사
<첨부>
- ISSUE #142
>  FILMDOMS #142 댓글 좋아요, 아티클 좋아요, 에디터 이미지 삽입, 클립 보드 복사

- components/views/Article/Main/BoardContainer/ArticleBoard/Board/Board.tsx
- components/views/Article/Main/BoardContainer/SearchBoardContainer.tsx
- components/views/Article/Main/BoardContainer/index.ts
- components/views/Article/Main/CriticContainer.tsx
- components/views/Article/Main/SearchArticleContainer.tsx
- components/views/Article/Main/SearchForm/SearchForm.tsx
- components/views/Article/Main/SearchForm/constants.ts
- components/views/Search/SearchContainer.tsx
- pages/404/index.tsx
- pages/search/[category]/[method]/index.tsx
- services/article/apis.ts
- services/article/queries.ts
- services/queryKeys.ts
FILMDOMS #142 검색 구현
<작업 내용>
- 검색 항목 구현
=> push로 search path 통해 param을 보내는 것으로 보임
-> SearchContainer를 새롭게 구성
<첨부>
- ISSUE #142
> FILMDOMS #142 검색 구현

- components/views/Auth/SignIn/SignIn.tsx
- next.config.js
- pages/auth/google.tsx
- services/api/utils.ts
제목 : FILMDOMS fix 도메인 수정
<작업 내용>
- 서버 url 수정
<첨부>
> FILMDOMS fix 도메인 수정

- components/views/Article/Main/Slide/Slider/data.ts
- components/views/Layout/Header/Avatar/Avatar.tsx
- pages/auth/google.tsx
- pages/auth/logout.tsx
- yarn.lock
제목 : FILMDOMS 정기 병합 작업
<작업 내용>
- 정기 병합 작업
<첨부>
> FILMDOMS 정기 병합 작업

- components/common/Modal/ProfileModal.tsx
- components/views/Article/Main/BoardContainer/BoardContainer.tsx
- components/views/Auth/Profile/hooks/useMyProfileBox.tsx
- components/views/Home/FilmUniverse/FilmUniverse.tsx
- components/views/Layout/Header/Avatar/Avatar.tsx
- components/views/Layout/Header/Avatar/ProfileBox/ProfileBox.tsx
- components/views/Layout/Header/Avatar/ProfileBox/index.ts
- components/views/Layout/Header/Avatar/hooks/useContextMenu.ts
- components/views/Layout/Header/Header.tsx
- hooks/useProfileModal.ts
- states/index.ts
제목 : FILMDOMS #(IssueNumber) [포괄적 제목]
<작업 내용>
- 컨텍스트 메뉴 프로필 박스
- film universe alignment
- critic content
<첨부>
> FILMDOMS feat: 컨텍스트 메뉴 프로필 박스, film universe align, critic content

- components/views/Article/Main/BoardContainer/ArticleBoard/CriticBoard.tsx
- components/views/Article/Main/BoardContainer/BoardContainer.tsx
- components/views/Article/Write/EditorContainer.tsx
- components/views/Article/Write/UpdateEditorContainer.tsx
- components/views/Home/Critic/Critic.tsx
- components/views/Home/Critic/CriticList.tsx
- components/views/Home/FilmUniverse/FilmUniverse.tsx
- components/views/Home/FilmUniverse/FilmUniverseList.tsx
- components/views/Layout/Header/Avatar/Avatar.tsx
- mocks/handlers/article/data/filmUniverse.ts
- types/pages/article.d.ts
- types/pages/main.d.ts
- utils/convertStringToHtml.ts
제목 :  FILMDOMS 정기 병합 작업
<작업 내용>
- 정기 병합 작업
<첨부>
>  FILMDOMS 정기 병합 작업

- components/common/Editor/Editor.tsx
- components/views/Article/Detail/Comment/ChildCommentItem.tsx
- components/views/Article/Detail/Comment/CommentContainer.tsx
- components/views/Article/Detail/Comment/CommentItem.stories.tsx
- components/views/Article/Detail/Comment/CommentItem.tsx
- components/views/Article/Main/Slide/Slider/Slider.tsx
- components/views/Article/Main/Slide/Slider/data.ts
- components/views/Article/Write/EditorContainer.tsx
- components/views/Article/Write/UpdateEditorContainer.tsx
- components/views/Auth/SignIn/SignIn.tsx
- components/views/MyPage/MyPageContainer.tsx
- components/views/MyPage/ProfileContainer.tsx
- components/views/MyPage/UserActivitySection/ArticleContainer/ArticleContainer.tsx
- components/views/MyPage/UserActivitySection/CommentContainer/CommentContainer.tsx
- components/views/MyPage/UserInfoSection/UserInfoSection.tsx
- hooks/useRouterChange.ts
- pages/_app.tsx
제목: FILMDOMS 대댓글 수정 삭제, 세부 디자인 수정 사항
<첨부>
> FILMDOMS 대댓글 수정 삭제, 세부 디자인 수정 사항

- components/views/Article/Detail/ArticleDetailContainer.tsx
- components/views/Article/Detail/Comment/ChildCommentItem.tsx
- components/views/Article/Detail/Comment/CommentContainer.tsx
- components/views/Article/Detail/Comment/CommentItem.stories.tsx
- components/views/Article/Detail/Comment/CommentItem.tsx
- services/article/queries.ts
제목 : FILMDOMS fix: 전반적인 수정사항 반영, 정기 병합
- 댓글, 대댓글 수정 사항 반영
<첨부>
> FILMDOMS fix: 전반적인 수정사항 반영, 정기 병합

- components/common/RouterBoundary/RouterBoundary.tsx
- components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
- components/views/Home/Banner/Banner.tsx
- components/views/Layout/Header/Avatar/Avatar.tsx
- services/myPage/apis.ts
- states/index.ts
> FILMDOMS #168 소셜 로그인 관련 이슈들을 처리합니다

- components/common/RouterBoundary/RouterBoundary.tsx
- components/views/Auth/SignIn/SignIn.tsx
- components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
- components/views/Home/Banner/Banner.tsx
- components/views/Layout/Header/Avatar/Avatar.tsx
- components/views/MyPage/MyPageContainer.tsx
- pages/auth/logout.tsx
- services/myPage/apis.ts
- services/myPage/queries.ts
- services/queryKeys.ts
- states/index.ts
<작업 내용>
- 소셜, 일반 유저 정보를 동시에 가져와서 처리합니다.
<첨부>
- ISSUE #168
> FILMDOMS #168 소셜로그인, 일반로그인 profile 조회를 동시에 수행합니다

- components/common/RouterBoundary/RouterBoundary.tsx
- components/views/Auth/SignIn/SignIn.tsx
- components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
- components/views/Home/Banner/Banner.tsx
- components/views/Layout/Header/Avatar/Avatar.tsx
- pages/auth/logout.tsx
- states/index.ts
<작업 내용>
- main에 적용되지 않은 변경 파일을 적용합니다.
<첨부>
- ISSUE #168
> hotfix: 변경되지 않은 파일을 변경합니다

- components/common/RouterBoundary/RouterBoundary.tsx
- components/views/Auth/SignIn/SignIn.tsx
- components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
- components/views/Home/Banner/Banner.tsx
- components/views/Layout/Header/Avatar/Avatar.tsx
- pages/auth/logout.tsx
- services/myPage/apis.ts
- states/index.ts
> FILMDOMS 최종 빌드 테스트, 에러 수정

- pages/_document.tsx
<작업 내용>
- 구글, 네이버 메타 태그를 추가합니다
<첨부>
- ISSUE #178
> FILMDOMS #178 구글, 네이버 메타 태그를 추가합니다

- pages/_document.tsx
- pages/about/index.tsx
제목 : FILMDOMS fix: og
<작업 내용>
- og 헤드 고정
> FILMDOMS fix: og

- pages/_app.tsx
- pages/_document.tsx
- public/robots.txt
제목: FILMDOMS fix: filmdoms issue resolve
<작업 내용>
- robots.txt
```typescript
NEXT_PUBLIC_NAVER_SITE_VERIFICATION=b4bfad55f5b0004677f55afa4a9c0a715ddf8cb9
NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION=Hvb2wMyklXkCej_4lFCpfNLSjX2CwEIdbbCzUG31vbw
NEXT_PUBLIC_DESCRIPTION=영화인의 모든 것, 필름덤즈
NEXT_PUBLIC_OG_TYPE=website
NEXT_PUBLIC_OG_TITLE=필름덤즈
NEXT_PUBLIC_OG_DESCRIPTION=영화인의 모든 것, 필름덤즈
NEXT_PUBLIC_OG_IMAGE=/og-image.png
NEXT_PUBLIC_OG_SITE_NAME=필름덤즈
```
<첨부>
> FILMDOMS fix: filmdoms issue resolve

- pages/_document.tsx
> feat: title 추가
